name: 'Update Azure API Management'
description: 'This GitHub Action allows you to update your Azure API Management api from an OpenAPI endpoint or file.'
author: 'Solidify'
inputs:
  swaggerPath:
    required: true
    description: 'URL or Path to Swagger'
  apiManagementEndpointUrl:
    required: true
    description: 'APIM endpoint URL'
  creds:
    required: true
    description: 'APIM credentials'
  swaggerType:
    required: true
    description: 'Swagger type [json or yaml]'
  swaggerPathType:
    required: true
    description: 'Swagger path type [url or local]'
  apimPath:
    required: false
    description: 'APIM Path Property. See https://docs.microsoft.com/en-us/rest/api/apimanagement/current-ga/apis/create-or-update?source=recommendations&tabs=HTTP'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: book-open
  color: black
